### ISSUE TITLE
"Connect With Slack" in settings does nothing

### ISSUE THREAD

**Issue by dkhokhlov** [scleriot/slack-reactions-notification#1] opened 2022-03-23 08:19 UTC
"Connect With Slack" in settings does nothing
is it known issue?
![image](https://user-images.githubusercontent.com/7530150/159654267-7ca7468a-7774-421a-b4d1-1a50a35736f4.png)

**Comment by fredfies** [comment] 2022-07-19 13:59
> "Connect With Slack" in settings does nothing is it known issue?"

It still doesn't work.. :-/

**Comment by maciej-skurznica** [comment] 2022-08-01 17:35
I was wondering why mine doesn't work. Here is the answer 😝

**Comment by Manaaia** [comment] 2022-08-02 16:03
Same here..

**Comment by scleriot** [comment] 2022-08-03 15:40
Hey everyone,

this was an issue with the auth server, it's now fixed!

Let me know if that works again

**Comment by Manaaia** [comment] 2022-08-03 15:49
It works! Thanks @scleriot :)

**Closed as completed** 2022-08-05 09:28 UTC

**Comment by camgatz87** [comment] 2023-02-17 16:40
Hi @scleriot the issue is back, could you please take a look when feasible?

**Comment by scleriot** [comment] 2023-02-20 09:34
Sorry for the issue, SSL cert was not renewing properly, it's back!

**Comment by camgatz87** [comment] 2023-09-15 17:00
Hi @scleriot sorry to say that the issue is back again. I cannot deploy a slack app because of my organization's policy, so I depend on your server. Could you please take a look when it's convenient for you?

**Comment by sam272** [comment] 2023-10-25 17:47
@scleriot any update on getting this issue resolved?

**Comment by ansgarschulte** [comment] 2024-06-05 08:15
Still not working
